### ISSUE TITLE
在项目的Jar包中包含Mybatis的Xml文件，会导致sql绑定失效。

### ISSUE THREAD

**Issue by YangAoLib** [SweetInk/jrebel-mybatisplus-idea-plugin#8]
## 如何产生的错误

在项目中Jar包中有Mybatis的Xml，并且有调用对应xml的Controller，在项目中调用Jar包中的Controller，会出现SQL绑定异常

## 重现方法
[报错项目](https://github.com/YangAoLib/jrebel-mybatisplus-idea-plugin--jar-has-xml)
我做了一个简单的demo，重现错误，README中包含重现的步骤。

## 版本

IDEA：IntelliJ IDEA 2023.3.6 (Ultimate Edition)  Build #IU-233.15026.9, built on March 21, 2024
Jrebel：2024.1.2
jrebel-mybatisplus-idea-plugins：0.0.5

**Comment by SweetInk** [comment]
你的配置 `application.yml`中关于`mapper-locations`配置貌似错了。
```yml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
```
应该为`mapper-locations: classpath*:*Mapper.xml`

因为你的jar包`jar-has-xml-0.0.1-SNAPSHOT.jar` 展开后如下，`TestMapper.xml` 没有放置在`mapper`目录下

![image](https://github.com/SweetInk/jrebel-mybatisplus-idea-plugin/assets/8621607/7be86e45-40c2-404e-9308-e75692706a1e)
